version: 2.1

jobs:
    build:
        docker:
            - image: circleci/rust:1.36.0
        steps:
            - checkout
            - run: cargo test --all
            - run: cargo run --example basic_blue
            - run: cargo doc --all
            - run: cargo build
            - run: cargo build --release
